//Thong tin nha hang
export const FETCH_ITEMCUSTOMER = 'FETCH_ITEMCUSTOMER';
export const ADD_ITEMCUSTOMER = 'ADD_ITEMCUSTOMER';
export const UPDATE_ITEMCUSTOMER= 'UPDATE_ITEMCUSTOMER';
export const DELETE_ITEMCUSTOM = 'DELETE_ITEMCUSTOM'; 
export const FILTER_ITEMCUSTOMER = 'FILTER_ITEMCUSTOMER';
export const SET_FILTER = 'SET_FILTER';

//blog
export const FETCH_ITEMBLOG = 'FETCH_ITEMBLOG';
export const UPDATE_ITEMPOST = 'UPDATE_ITEMPOST';
export const FETCH_LINK_BLOGS = 'FETCH_LINK_BLOGS';
export const RESULT_LINK_BLOGS = 'RESULT_LINK_BLOGS';
export const  GET_INFO_RESTAURANT= 'GET_INFO_RESTAURANT';
export const SET_EMPTY = 'SET_EMPTY';
export const LOCATION_POST = 'LOCATION_POST';



//Thong Ke
export const LOAD_DEFAULT_BAR_CHART = 'LOAD_DEFAULT_BAR_CHART';
export const LOAD_DEFAULT_CHART_DATE = 'LOAD_DEFAULT_CHART_DATE';
export const SET_DATE_CHART = 'SET_DATE_CHART';
export const LOAD_CURRENT_BAR_CHART = 'LOAD_CURRENT_BAR_CHART';
export const LOAD_ALL_TRACKING = 'LOAD_ALL_TRACKING';


//Truyen Thong
export const TRUYENTHONG = {
    FECTH_COMMUNICATION: 'FECTH_COMMUNICATION',
    ADD_COMMUNICATION: 'ADD_COMMUNICATION',
    FILTER_NOTIFI_CATEGORY: 'FILTER_NOTIFI_CATEGORY',
    CATEGORY_SELECTED: 'CATEGORY_SELECTED',
    DELETE_COMMUNICATION: 'DELETE_COMMUNICATION',
    UPDATE_IS_ACTIVE: 'UPDATE_IS_ACTIVE',
    LOCATIONS_SELECTED: 'LOCATIONS_SELECTED',
    UPDATE_SORTID: 'UPDATE_SORTID'
}


//Restaurant
export const RESTAURANT = {
    GET_LINK_BLOGS: 'GET_LINK_BLOGS',
    SAVE_CONTROL_BLOG: 'SAVE_CONTROL_BLOG',
    GET_ALL_RESTAURANT: 'GET_ALL_RESTAURANT',
    SAVE_RESTAURANT_FILTER: 'SAVE_RESTAURANT_FILTER',
    UPDATE_ITEMPOST: 'UPDATE_ITEMPOST',
    SETTING_COLOR : 'SETTING_COLOR'
}

//Caidat
export const SETTING = {
    SET_ARR_SETTING: 'SET_ARR_SETTING',
    FETCH_SETTING: 'FETCH_SETTING',
    UPDATE_SETTING: 'UPDATE_SETTING',
    CREATE_SETTING: 'CREATE_SETTING',
}

//API Tracking
export const TRACKING = {
    FECTH_DATA_TRACKING: 'FECTH_DATA_TRACKING'
}